###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: esp32-s3-box-3-5a7854
  friendly_name: ESP32 S3 Box 3 5a7854 Base

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf

###############################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}

# Enable Home Assistant API
api:
  encryption:
    key: lVB3Eddi7iRL1fYdX5PHH/0htdZgPkOCMZbuAWlgTgc=
ota:
  platform: esphome
  
# Enable logging
logger:

###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
