###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: m5stack-atom-lite-315bd0
  friendly_name: Study Atom Lite Speaker 315bd0

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: m5stack-atom
  framework:
    type: arduino # Required for I2S audio

###############################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}
  power_save_mode: NONE
#  use_address: ${name}.tgv.home

# Enable Home Assistant API
api:

ota:
  platform: esphome

# Enable logging
logger:

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: None
    dac_type: external
    i2s_dout_pin: GPIO25
    mode: mono

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    id: top_button
    name: Button
    # on_click:
    #   then:
    #     - media_player.toggle: media_out

light:
  - platform: fastled_clockless
    id: led
    name: None
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb

###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

safe_mode:

button:
  - platform: shutdown
    id: shutdown_btn
    name: "Shutdown"
  - platform: restart
    id: restart_btn
    name: "Restart"
  - platform: safe_mode
    id: safe_mode_btn
    name: Safe Mode Boot
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
