###############################################################################
# NOTES #######################################################################
###############################################################################

# SDCard
# 3 SS
# 4 MOSI
# 5 SCK
# 6 MISO
# 7 CD

# ePaper Panel
# 35 BUSY
# 36 RST
# 37 DC
# 38 CS
# 39 CLK
# 40 MOSI

# LEDs
# 2 LED

# Other
# 41 Input 1
# 42 Input 2
# 8 Relay

# 21 Relay

###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: revk-epd-731bac
  friendly_name: RevK EPD 731bac Base

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    board_build.flash_size: 8MB

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
   
psram:
  mode: quad
  speed: 80MHz


################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}
  power_save_mode: NONE
#  use_address: ${name}.tgv.home

captive_portal:

# Enable Home Assistant API
api:

ota:
  platform: esphome

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"


light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO2
    num_leds: 25
    chipset: ws2812
    name: "Edge LEDs"
    id: edge_leds

time:
  - platform: sntp
    id: sntp_time
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
    on_time:
      - seconds: 0, 10, 20, 30, 45, 50
        minutes: /1
        then:
          - logger.log: "LEDs Off"
          - light.addressable_set:
              id: edge_leds
              range_from: 0
              range_to: 24
              red: 0%
              green: 0%
              blue: 0%
      - seconds: 5, 15, 25, 35, 45, 55
        minutes: /1
        then:
          - logger.log: "LEDs On"
          - light.addressable_set:
              id: edge_leds
              range_from: 0
              range_to: 24
              red: 25%
              green: 25%
              blue: 25%

number:
  - platform: template
    id: led_counter
    min_value: 0
    max_value: 24
    step: 1
    disabled_by_default: true
    internal: true
    optimistic: true