###############################################################################
# NOTES #######################################################################
###############################################################################

# SDCard
# 12 SS
# 13 MOSI
# 14 SCK
# 15 MISO
# 17 CD
# 18 CHG

# LEDs
# 39 Status LED
# 8 Record LED

# Speaker
# https://www.analog.com/media/en/technical-documentation/data-sheets/MAX98357A-MAX98357B.pdf
# 38 Speaker power on
# 35 Speaker LR clock
# 36 Speaker Bit clock
# 37 Speaker Data

# Mic
# https://www.lcsc.com/datasheet/lcsc_datasheet_2312010321_TDK-InvenSense-ICS-43434_C5656610.pdf
# 7 Microphone Data / SD
# 5 Microphone Clock / SCK
# 6 Microphone WS (not set for PDM)

# Other
# 11 Battery Charging
# 1 Button

###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: revk-recorder-74b2b0
  friendly_name: RevK Recorder 74b2b0 Base

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    board_build.flash_size: 8MB

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
   
psram:
  mode: quad
  speed: 80MHz


################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}

captive_portal:

# Enable Home Assistant API
api:

ota:
  platform: esphome

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"


light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO39
    num_leds: 2
    rmt_channel: 0
    chipset: ws2812
    name: "Status Light"
    id: status_light
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO8
    num_leds: 2
    rmt_channel: 1
    chipset: ws2812
    name: "Record Light"
    id: record_light

i2s_audio:
  - id: i2s_mic
    i2s_lrclk_pin: GPIO6
    i2s_bclk_pin: GPIO5
  - id: i2s_spk
    i2s_lrclk_pin: GPIO35
    i2s_bclk_pin: GPIO36


microphone:
  - platform: i2s_audio
    id: adc_mic
    i2s_audio_id: i2s_mic
    adc_type: external
    i2s_din_pin: GPIO7

speaker:
  - platform: i2s_audio
    id: dac_spk
    i2s_audio_id: i2s_spk
    dac_type: external
    i2s_dout_pin: GPIO37

binary_sensor:
  - platform: gpio
    id: pushbutton
    pin: GPIO1
    on_press:
      then:
        - logger.log: "Button Press"
    on_release:
      then:
        - logger.log: "Button Release"
  - platform: gpio
    id: charging
    pin: GPIO11
    on_press:
      then:
        - logger.log: "Charging Press"
    on_release:
      then:
        - logger.log: "Charging Release"

time:
  - platform: sntp
    id: sntp_time
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
    on_time:
      - seconds: 0, 10, 20, 30, 45, 50
        minutes: /1
        then:
          - logger.log: "Ping 0"
          - light.addressable_set:
              id: status_light
              range_from: 0
              range_to: 0
              red: 0%
              green: 0%
              blue: 0%
          - light.addressable_set:
              id: status_light
              range_from: 1
              range_to: 1
              red: 10%
              green: 0%
              blue: 0%
          - light.addressable_set:
              id: record_light
              range_from: 0
              range_to: 0
              red: 0%
              green: 0%
              blue: 0%
          - light.addressable_set:
              id: record_light
              range_from: 1
              range_to: 1
              red: 0%
              green: 10%
              blue: 0%
      - seconds: 5, 15, 25, 35, 45, 55
        minutes: /1
        then:
          - logger.log: "Ping 5"
          - light.addressable_set:
              id: status_light
              range_from: 0
              range_to: 0
              red: 0%
              green: 0%
              blue: 10%
          - light.addressable_set:
              id: status_light
              range_from: 1
              range_to: 1
              red: 0%
              green: 0%
              blue: 0%
          - light.addressable_set:
              id: record_light
              range_from: 0
              range_to: 0
              red: 10%
              green: 10%
              blue: 10%
          - light.addressable_set:
              id: record_light
              range_from: 1
              range_to: 1
              red: 0%
              green: 0%
              blue: 0%