###############################################################################
# NOTES #######################################################################
###############################################################################

# https://www.waveshare.com/wiki/ESP32-S3-GEEK

# ST7789P3
# LCD DC - 8
# LCD CS - 10
# LCD CLK - 12
# LCD MOSI - 11
# LCD RST - 9
# LCD BL - 7


###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-geek-cc95c8
  friendly_name: WaveShare Geek cc95c8 Base

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
   
psram:
  mode: quad
  speed: 80MHz


################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}
#  use_address: ${name}.tgv.home

captive_portal:

# Enable Home Assistant API
api:

ota:
  platform: esphome

# Enable logging
logger:

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################

spi:
  - id: spi_lcd
    clk_pin: GPIO12
    mosi_pin: GPIO11
    #miso_pin: GPIOXX

output:
  - platform: ledc # Define a PWM output on the ESP32
    pin: GPIO7
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON


###############################################################################
# VARIABLES & SCRIPTS #########################################################
###############################################################################






###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

###############################################################################
# SENSORS #####################################################################
###############################################################################

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  on_ble_advertise:
    - mac_address:
        - "11:11:11:11:11:11"
        - "22:22:22:22:22:22"
      then:
        - lambda: |-
            ESP_LOGD("ble_adv", "New BLE device");
            ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
                ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
            ESP_LOGD("ble_adv", "  Advertised service data:");
            for (auto data : x.get_service_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }
            ESP_LOGD("ble_adv", "  Advertised manufacturer data:");
            for (auto data : x.get_manufacturer_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }


###############################################################################
# DISPLAY #####################################################################
###############################################################################

font:
  - file:
      type: gfonts
      family: Montserrat
      weight: 500
    id: text_large
    size: 30
    extras:
      file:
        type: gfonts
        family: Montserrat
        weight: 500
      glyphs: [ "'", "£" ]

display:
  - platform: ili9xxx
    model: ST7796 #ST7789V
    id: lcd_display
    spi_id: spi_lcd
    dc_pin: GPIO8
    reset_pin: GPIO9
    invert_colors: false
    color_order: rgb
    #show_test_card: true
    dimensions:
      width: 240
      height: 135
    # init_sequence:
    #   - [0x11, 120] ##
    #   - [0x36, 0x00]
    #   - [0x3A, 0x05]
    #   - [0xB2, 0x0C, 0x0C, 0x00, 0x33, 0x33]
    #   - [0xb7, 0x56]
    #   - [0xbb, 0x1d]
    #   - [0xc0, 0x2c]
    #   - [0xc2, 0x01]
    #   - [0xc3, 0x0f]
    #   - [0xc6, 0x0f]
    #   - [0xd0, 0xa7]
    #   - [0xd0, 0xa4, 0xa1]
    #   - [0xd6, 0xa1]
    #   - [0xe0, 0xF0, 0x02, 0x07, 0x05, 0x06, 0x14, 0x2F, 0x54, 0x46, 0x38, 0x13, 0x11, 0x2E, 0x35]
    #   - [0xe1, 0xF0, 0x08, 0x0C, 0x0C, 0x09, 0x05, 0x2F, 0x43, 0x46, 0x36, 0x10, 0x12, 0x2C, 0x32]
    #   - [0x21]
    #   - [0x29] ##
    #   - [0x2c, 100]
    #   - [0x2a, 0x00, 0x00, 0x01, 0x3f]
    #   - [0x2b, 0x00, 0x00, 0x00, 0xef]
    #   - [0x2c]
    #   - [0xFF,0xFF]

    lambda: |-
      // Panel
      int panel_x = it.get_width();
      int panel_y = it.get_height();
      int panel_x_mid = panel_x / 2;
      int panel_y_mid = panel_y / 2;

      it.printf(panel_x_mid, panel_y_mid, id(text_large), TextAlign::CENTER, "X");
