###############################################################################
# NOTES #######################################################################
###############################################################################

# https://www.waveshare.com/wiki/ESP32-S3-GEEK

# ST7789P3
# LCD DC - 8
# LCD CS - 10
# LCD CLK - 12
# LCD MOSI - 11
# LCD RST - 9
# LCD BL - 7


###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-geek-cc95c8
  friendly_name: WaveShare Geek cc95c8 Base

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
   
psram:
  mode: quad
  speed: 80MHz


################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}

captive_portal:

# Enable Home Assistant API
api:

ota:
  platform: esphome

# Enable logging
logger:

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################

spi:
  - id: spi_lcd
    clk_pin: GPIO12
    mosi_pin: GPIO11
    #miso_pin: GPIOXX

output:
  - platform: ledc # Define a PWM output on the ESP32
    pin: GPIO7
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON


###############################################################################
# VARIABLES & SCRIPTS #########################################################
###############################################################################






###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

###############################################################################
# SENSORS #####################################################################
###############################################################################




###############################################################################
# DISPLAY #####################################################################
###############################################################################

display:
  - platform: ili9xxx
    model: ST7789V
    id: lcd_display
    spi_id: spi_lcd
    dc_pin: GPIO8
    reset_pin: GPIO9
    invert_colors: false
    color_order: rgb
    show_test_card: true