###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-touch7-ab5204
  friendly_name: WaveShare Touch7 Base ab5204


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"

      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: "y"
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: "y"
      CONFIG_ESPTOOLPY_FLASHFREQ_120M: "y" #[should align with PSRAM]
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_IDF_EXPERIMENTAL_FEATURES: "y"
      CONFIG_SPIRAM_SPEED_120M: "y" #[should align with FLASH]
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_COMPILER_OPTIMIZATION_PERF: "y"

      CONFIG_LV_MEM_CUSTOM: "y"
      CONFIG_LV_MEMCPY_MEMSET_STD: "y"
      CONFIG_LV_ATTRIBUTE_FAST_MEM: "y"
    advanced:
      enable_idf_experimental_features: true

psram:
  mode: octal
  speed: 120MHz


################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}
  power_save_mode: NONE
#  use_address: ${name}.tgv.home

captive_portal:

# Enable Home Assistant API
api:

ota:
  platform: esphome

# Enable logging
logger:
  hardware_uart: uart0
#  level: VERBOSE


button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all
