###############################################################################
# NOTES #######################################################################
###############################################################################

# https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.28


# https://esphome.io/components/i2c
# https://esphome.io/components/uart

# https://esphome.io/components/sensor/ld2420
# 1 - 3v3 - VCC - Board Pin6
# 2 - GND - GND - Board Pin5
# 3 - OT1 - Serial Tx (to ESP Rx) - Board Pin8
# 4 - RX - Serial Rx (to ESP Tx) - Board Pin7
# 5 - OT2 - Presence Signal Output - N/C


###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-touch-2d0040
  friendly_name: WaveShare Touch LCD 2d0040

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_upload.maximum_ram_size: 524288
  on_boot:
    - delay: 5s
    - lvgl.widget.hide: boot_screen

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: quad
  speed: 80MHz


################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}
  power_save_mode: NONE
#  use_address: ${name}.tgv.home

captive_portal:

# Enable Home Assistant API
api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus
ota:
  platform: esphome

# Enable logging
logger:
  hardware_uart: uart0
#  level: VERBOSE

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################

spi:
  - id: spi_lcd
    mosi_pin: GPIO11
    clk_pin: GPIO10
    miso_pin: GPIO12
    interface: any
#  - id: spi_touch
#    mosi_pin: GPIO4
#    clk_pin: GPIO6
#    miso_pin: GPIO3
#    interface: any

i2c:
  sda: GPIO06
  scl: GPIO07
  scan: true
  id: bus_a

uart:
  id: ld2420_uart
  tx_pin: GPIO15
  rx_pin: GPIO16
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

output:
  - platform: ledc # Define a PWM output on the ESP32
    pin: GPIO02
    id: backlight_pwm

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: display_backlight
    restore_mode: ALWAYS_ON

ld2420:

###############################################################################
# VARIABLES & SCRIPTS #########################################################
###############################################################################

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"

number:
  - platform: ld2420
    presence_timeout:
      name: mmWave Presence Timeout
    min_gate_distance:
      name: mmWave Gate Minimum
    max_gate_distance:
      name: mmWave Gate Maximum
    gate_select:
      name: mmWave Gate Select
    still_threshold:
      name: mmWave Still Threshold Value
    move_threshold:
      name: mmWave Move Threshold Value


  - platform: template
    id: rate_num_min
    min_value: -10
    max_value: 100
    step: 1
    disabled_by_default: true
    internal: true
    optimistic: true
    on_value:
      then:
        - lvgl.indicator.update:
            id: val_arc_minmax
            start_value: !lambda return (int) x;
        - logger.log:
            format: "Updating Arc Min Rate to %d"
            args: [ '(int) x' ]
        - lvgl.indicator.update:
            id: val_arc_minmax
            end_value: !lambda return (int) id(rate_num_max).state;
        - logger.log:
            format: "Updating Arc Max Rate to %d"
            args: [ '(int) id(rate_num_max)' ]

  - platform: template
    id: rate_num_max
    min_value: -10
    max_value: 100
    step: 1
    disabled_by_default: true
    internal: true
    optimistic: true
    on_value:
      then:
        - lvgl.indicator.update:
            id: val_arc_minmax
            start_value: !lambda return (int) id(rate_num_min).state;
        - logger.log:
            format: "Updating Arc Min Rate to %d"
            args: [ '(int) id(rate_num_min)' ]
        - lvgl.indicator.update:
            id: val_arc_minmax
            end_value: !lambda return (int) x;
        - logger.log:
            format: "Updating Arc Max Rate to %d"
            args: [ '(int) x' ]



time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"

###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all


  - platform: ld2420
    apply_config:
      name: mmWave Apply Config
    factory_reset:
      name: mmWave Factory Reset
    restart_module:
      name: mmWave Restart
    revert_config:
      name: mmWave Undo

select:
  - platform: ld2420
    operating_mode:
      name: mmWave Mode

###############################################################################
# SENSORS #####################################################################
###############################################################################

binary_sensor:
  - platform: touchscreen
    name: ScreenLeft
    x_min: 0
    x_max: 119
    y_min: 0
    y_max: 240
    on_press:
      then:
        - lvgl.page.previous:
            animation: OUT_RIGHT
            time: 300ms

  - platform: touchscreen
    name: ScreenRight
    x_min: 120
    x_max: 240
    y_min: 0
    y_max: 240
    on_press:
      then:
        - lvgl.page.next:
            animation: OUT_LEFT
            time: 300ms

  - platform: ld2420
    has_target:
      name: mmWave Presence
      id: mmwave_presence
      on_release:
        then:
          - logger.log: "LVGL is idle"
          - light.turn_off: display_backlight
          - lvgl.pause:
              show_snow: true
      on_press:
        then:
          - if:
              condition: lvgl.is_paused
              then:
                - logger.log: "LVGL resuming"
                - lvgl.resume:
                - lvgl.page.show:
                    id: energy_page
                - lvgl.widget.redraw:
                - light.turn_on: display_backlight

###############################################################################

text_sensor:

  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

###############################################################################

sensor:
    #Device UPTIME
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

    #Device CPU Speed
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

    #Device Memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

    #Device RSSI
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"


  - platform: ld2420
    moving_distance:
      name : mmWave Moving Distance
      filters:
        - throttle_average: 15s
        - filter_out: nan



    # HomeAssistant Sensors

  - platform: homeassistant
    entity_id: sensor.octopus_rates
    attribute: prev_rate_value
    id: octopus_prev_rate_value

  - platform: homeassistant
    entity_id: sensor.octopus_rates
    attribute: curr_rate_value
    id: octopus_curr_rate_value
    on_value:
      then:
        - lvgl.indicator.update:
            id: val_needle_current_rate
            value: !lambda return (int) round(x * 100);
        - lvgl.label.update:
            id: val_text_current_rate
            text:
              format: "%.1f"
              args: [ 'x * 100' ]

  - platform: homeassistant
    entity_id: sensor.octopus_rates
    attribute: next_rate_value
    id: octopus_next_rate_value
    on_value:
      then:
        - lvgl.indicator.update:
            id: val_needle_next_rate
            value: !lambda return (int) round(x * 100);

  - platform: homeassistant
    entity_id: sensor.octopus_rates
    attribute: min_rate
    id: octopus_min_rate
    on_value:
      then:
        - number.set:
            id: rate_num_min
            value: !lambda return (int) round(x * 100);
        - logger.log:
            format: "Updating Number Min Rate to %d"
            args: [ '(int) round(x * 100)' ]
        # - lvgl.indicator.update:
        #     id: val_arc_minmax
        #     start_value: !lambda return (int) round(x * 100);
        # - logger.log:
        #     format: "Updating Arc Min Rate to %d"
        #     args: [ '(int) round(x * 100)' ]

  - platform: homeassistant
    entity_id: sensor.octopus_rates
    attribute: max_rate
    id: octopus_max_rate
    on_value:
      then:
        - number.set:
            id: rate_num_max
            value: !lambda return (int) round(x * 100);
        - logger.log:
            format: "Updating Number Max Rate to %d"
            args: [ '(int) round(x * 100)' ]
        # - lvgl.indicator.update:
        #     id: val_arc_minmax
        #     end_value: !lambda return (int) round(x * 100);
        # - logger.log:
        #     format: "Updating Arc Max Rate to %d"
        #     args: [ '(int) round(x * 100)' ]

  
  - platform: homeassistant
    entity_id: sensor.octopus_rates
    attribute: average_rate
    id: octopus_average_rate

  - platform: homeassistant
    entity_id: sensor.octopus_energy_electricity_23l3520058_2700001750370_current_demand
    id: octopus_current_demand
    on_value:
      then:
        - lvgl.indicator.update:
            id: val_needle_current_demand
            value: !lambda return x;
        - lvgl.label.update:
            id: val_text_current_demand
            text:
              format: "%.0f"
              args: [ 'x' ]

################################################################################

touchscreen:
  - platform: cst816
    display: lcd_display
    id: my_touchscreen
    interrupt_pin: GPIO05
    reset_pin: GPIO13
    skip_probe: true
    on_touch:
      - lambda: |-
            ESP_LOGI("Touch:touch : ", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                touch.x, touch.y, touch.x_raw, touch.y_raw);
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.page.show:
                id: energy_page
            - lvgl.widget.redraw:
            - light.turn_on: display_backlight

display:
  - platform: ili9xxx
    model: GC9A01A
    dc_pin: GPIO08
    reset_pin: GPIO14
    id: lcd_display
    spi_id: spi_lcd
    invert_colors: true
    dimensions:
      height: 240
      width: 240
    #show_test_card: true
    auto_clear_enabled: false
    update_interval: never

lvgl:
  displays:
    - lcd_display
  touchscreens:
    - my_touchscreen
  on_idle:
    - timeout: 30s
      then:
        - lvgl.page.show: energy_page
    # - timeout: 5min
    #   then:
    #     - logger.log: "LVGL is idle"
    #     - light.turn_off: display_backlight
    #     - lvgl.pause:
    #         show_snow: true

  top_layer:
    widgets:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          height: 100%
          width: 100%
          align: CENTER
          bg_color: 0xffffff
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - spinner:
                align: CENTER
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
          on_press:
            - lvgl.widget.hide: boot_screen
      - obj:
          id: icon_screen
          x: 0
          y: 0
          height: 100%
          width: 100%
          align: CENTER
          bg_color: 0xffffff
          bg_opa: TRANSP
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - label:
                text: "\uF015" # HA Connectivity Icon
                id: lbl_hastatus
                align: BOTTOM_MID
                y: -10
                text_align: CENTER
                text_color: 0x0000FF

  pages:
    # - id: main_page
    #   skip: true
    #   widgets:
    #     - label:
    #         align: CENTER
    #         text: 'Hello World!'
    - id: energy_page
      widgets:
        - obj:
            x: 0
            y: 0
            height: 100%
            width: 100%
            align: CENTER
            bg_color: 0xFFFFFF
            border_width: 0
            pad_all: 0
            widgets:
              - meter: # Current rate meter
                  height: 100%
                  width: 100%
                  border_width: 0
                  pad_all: 0
                  bg_opa: TRANSP
                  align: CENTER
                  scales:
                    - range_from: -20
                      range_to: 100
                      angle_range: 120
                      rotation: 120
                      ticks:
                        width: 1
                        count: 13
                        length: 5
                        color: 0x000000
                        major:
                          stride: 2
                          width: 2
                          length: 10
                          color: 0x404040
                          label_gap: 10
                      indicators:
                        - arc:
                            id: val_arc_minmax
                            color: 0xff0000
                            end_value: 10
                            r_mod: 0
                            start_value: -10
                            width: 5
                        - line:
                            id: val_needle_current_rate
                            color: 0x0000bd
                            width: 4
                            r_mod: 12
                            value: 0
                        - line:
                            id: val_needle_next_rate
                            color: 0x666666
                            width: 2
                            r_mod: 12
                            value: 0

              - meter: # Current demand meter
                  height: 100%
                  width: 100%
                  border_width: 0
                  pad_all: 0
                  bg_opa: TRANSP
                  align: CENTER
                  scales:
                    - range_from: 10000
                      range_to: 0
                      angle_range: 120
                      rotation: 300
                      ticks:
                        width: 1
                        count: 11
                        length: 5
                        color: 0x000000
                        major:
                          stride: 2
                          width: 2
                          length: 10
                          color: 0x404040
                          label_gap: 10
                      indicators:
                        - line:
                            id: val_needle_current_demand
                            color: 0xbd0000
                            width: 4
                            r_mod: 12
                            value: 0
                        - tick_style:
                            start_value: 10000
                            end_value: 0
                            color_start: 0xbd0000
                            color_end: 0x00bd00
                            width: 1

              - obj: # Cover the middle part of meter indicator line
                  height: 146
                  width: 146
                  radius: 72
                  align: CENTER
                  border_width: 0
                  bg_color: 0xFFFFFF
                  pad_all: 0

              - label: # Current rate numeric indicator
                  id: val_text_current_rate
                  text_font: montserrat_26
                  align: CENTER
                  x: -35
                  y: 0
                  text: "0"
              - label: # Current rate unit label
                  text_font: montserrat_14
                  align: CENTER
                  x: -35
                  y: 25
                  text: "p/kWh"

              - label: # Current demand numeric indicator
                  id: val_text_current_demand
                  text_font: montserrat_26
                  align: CENTER
                  x: 35
                  y: 0
                  text: "0"
              - label: # Current demand unit label
                  text_font: montserrat_14
                  align: CENTER
                  x: 35
                  y: 25
                  text: "W"
