###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-touch7-ab5204
  friendly_name: WaveShare Touch7 LCD ab5204

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_upload.maximum_ram_size: 524288
  on_boot:
    - delay: 5s
    - lvgl.widget.hide: boot_screen
    - lvgl.page.show:
        id: main_page

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"

      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: "y"
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: "y"
      CONFIG_ESPTOOLPY_FLASHFREQ_120M: "y" #[should align with PSRAM]
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_IDF_EXPERIMENTAL_FEATURES: "y"
      CONFIG_SPIRAM_SPEED_120M: "y" #[should align with FLASH]
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_COMPILER_OPTIMIZATION_PERF: "y"

      CONFIG_LV_MEM_CUSTOM: "y"
      CONFIG_LV_MEMCPY_MEMSET_STD: "y"
      CONFIG_LV_ATTRIBUTE_FAST_MEM: "y"
    advanced:
      enable_idf_experimental_features: true

psram:
  mode: octal
  speed: 120MHz


################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}
  power_save_mode: NONE
#  use_address: ${name}.tgv.home
  on_connect:
    - lvgl.widget.show: lbl_wifistatus
  on_disconnect:
    - lvgl.widget.hide: lbl_wifistatus

captive_portal:

# Enable Home Assistant API
api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus
ota:
  platform: esphome

# Enable logging
logger:
  hardware_uart: uart0
#  level: VERBOSE


###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: True
  id: bus_a

ch422g:
  - id: ch422g_hub

###############################################################################
# VARIABLES & SCRIPTS #########################################################
###############################################################################

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"

###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

switch:    
  - platform: gpio
    id: display_backlight
    name: Display Backlight
    pin:
      ch422g: ch422g_hub
      number: 2
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_ON


###############################################################################
# SENSORS #####################################################################
###############################################################################

#binary_sensor:

#text_sensor:

sensor:
    #Device UPTIME
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

    #Device CPU Speed
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

    #Device Memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

    #Device RSSI
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # HomeAssistant Sensors



###############################################################################
# DISPLAY #####################################################################
###############################################################################

touchscreen:
  - platform: gt911
    id: my_touchscreen
    interrupt_pin: GPIO4
    reset_pin:
      ch422g: ch422g_hub
      number: 1
      mode: OUTPUT
    transform:
      mirror_x: true
      mirror_y: true
      swap_xy: false
    on_touch:
      - lambda: |-
            ESP_LOGI("Touch:touch : ", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                touch.x, touch.y, touch.x_raw, touch.y_raw);
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.page.show:
                id: main_page
            - lvgl.widget.redraw:
            - switch.turn_on: display_backlight

# Define display
display:
  - platform: rpi_dpi_rgb
    id: my_display
    update_interval: never
    auto_clear_enabled: false
    rotation: 180
    color_order: RGB
    pclk_frequency: 16MHZ
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    reset_pin:
      ch422g: ch422g_hub
      number: 3
#    enable_pin:
#      ch422g: ch422g_hub
#      number: 2  
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7


###############################################################################
# LVGL ########################################################################
###############################################################################

lvgl:
  #log_level: none #INFO
  #color_depth: 16
  #buffer_size: 25%
  #width: 800
  #height: 480
  #align: center
  disp_bg_color: 0xffffff

  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle:
    - timeout: 30s
      then:
        - lvgl.page.show: main_page
    - timeout: 15min
      then:
        - logger.log: "LVGL is idle"
        - switch.turn_off: display_backlight
        - lvgl.pause:
            show_snow: true

  theme:
    label:
      text_font: montserrat_14
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
    buttonmatrix:
      bg_opa: TRANSP
      border_color: 0x0077b3
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 0
      items: # set all your buttonmatrix buttons to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        text_font: montserrat_20
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x005580
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: 15%
      bg_color: 0xcccaca
      bg_opa: 15%
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 50
      text_font: montserrat_20

  top_layer:
    widgets:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          height: 100%
          width: 100%
          align: CENTER
          bg_color: 0xffffff
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - spinner:
                align: CENTER
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
          on_press:
            - lvgl.widget.hide: boot_screen

      - obj:
          id: icon_area
          styles: header_footer
          width: 100%
          pad_left: 20px
          pad_right: 20px
          pad_top: 10px
          border_width: 0
          layout:
            type: FLEX
            flex_flow: ROW
            flex_align_main: space_between
            flex_align_cross: center
            pad_column: 20px
          widgets:
            - label:
                text: "Hello"
                text_font: montserrat_24
                flex_grow: 1
                align: left_mid
            - label:
                text: "\uF015" # HA Connectivity Icon
                id: lbl_hastatus
                text_font: montserrat_24
                align: center
            - label:
                text: "\uF1EB" # WiFI Connectivity Icon
                id: lbl_wifistatus
                text_font: montserrat_24
                align: center

      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: button_matrix
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: main_page_btn
                text: "\uF015"
                on_press:
                  then:
                    lvgl.page.show: main_page
              - id: second_page_btn
                text: "2"
                on_press:
                  then:
                    lvgl.page.show: second_page
              - id: third_page_btn
                text: "3"
                on_press:
                  then:
                    lvgl.page.show: third_page
              - id: fourth_page_btn
                text: "4"
                on_press:
                  then:
                    lvgl.page.show: fourth_page
              - id: fifth_page_btn
                text: "5"
                on_press:
                  then:
                    lvgl.page.show: fifth_page

  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: 'First Page'
        # - obj: # Container for the Energy gauge?
        #     x: 10
        #     y: 60
        #     height: 200
        #     width: 200
        #     align: TOP_LEFT
        #     bg_color: 0xFFFFFF
        #     bg_opa: TRANSP
        #     border_width: 0
        #     pad_all: 0
        #     text_font: montserrat_10
        #     widgets:
        #       - meter: # Current rate meter
        #           height: 100%
        #           width: 100%
        #           border_width: 0
        #           pad_all: 0
        #           bg_color: 0xDEDEDE
        #           bg_opa: COVER
        #           align: CENTER
        #           scales:
        #             - range_from: -20
        #               range_to: 100
        #               angle_range: 120
        #               rotation: 120
        #               ticks:
        #                 width: 1
        #                 count: 13
        #                 length: 5
        #                 color: 0x000000
        #                 major:
        #                   stride: 2
        #                   width: 2
        #                   length: 10
        #                   color: 0x404040
        #                   label_gap: 15
        #               indicators:
        #                 - line:
        #                     id: val_needle_current_rate
        #                     color: 0xBD0000
        #                     width: 3
        #                     r_mod: -5
        #                     value: 0
        #                 - line:
        #                     id: val_needle_next_rate
        #                     color: 0x00BD00
        #                     width: 2
        #                     r_mod: -5
        #                     value: 0

        #             - range_from: 10000
        #               range_to: 0
        #               angle_range: 120
        #               rotation: 300
        #               ticks:
        #                 width: 1
        #                 count: 11
        #                 length: 5
        #                 color: 0x000000
        #                 major:
        #                   stride: 2
        #                   width: 2
        #                   length: 10
        #                   color: 0x404040
        #                   label_gap: 15
        #               indicators:
        #                 - line:
        #                     id: val_needle_current_demand
        #                     color: 0xBD0000
        #                     width: 3
        #                     r_mod: -5
        #                     value: 0
        #                 - tick_style:
        #                     start_value: 10000
        #                     end_value: 0
        #                     color_start: 0xbd0000
        #                     color_end: 0x00bd00
        #                     width: 1

        #       - obj: # Cover the middle part of meter indicator line
        #           height: 110
        #           width: 110
        #           radius: 55
        #           align: CENTER
        #           border_width: 0
        #           bg_color: 0xFFFFFF
        #           pad_all: 0

        #       - label: # Current rate numeric indicator
        #           id: val_text_current_rate
        #           text_font: montserrat_18
        #           align: CENTER
        #           x: -22
        #           y: -10
        #           text: "0"
        #       - label: # Current rate unit label
        #           text_font: montserrat_10
        #           align: CENTER
        #           x: -22
        #           y: 14
        #           text: "p/kWh"

        #       - label: # Current demand numeric indicator
        #           id: val_text_current_demand
        #           text_font: montserrat_18
        #           align: CENTER
        #           x: 22
        #           y: -10
        #           text: "0"
        #       - label: # Current demand unit label
        #           text_font: montserrat_10
        #           align: CENTER
        #           x: 22
        #           y: 14
        #           text: "W"

    - id: second_page
      #skip: true
      widgets:
        - label:
            align: CENTER
            text: 'Second Page'

    - id: third_page
      #skip: true
      widgets:
        - label:
            align: CENTER
            text: 'Third Page'

    - id: fourth_page
      #skip: true
      widgets:
        - label:
            align: CENTER
            text: 'Fourth Page'

    - id: fifth_page
      #skip: true
      widgets:
        - label:
            align: CENTER
            text: 'Fifth Page'